version: '3.8'

services:
  app:
    image: joshpigford/sims:latest
    volumes:
      - db-data:/app/db
    ports:
      - "5173:5173"
      - "8175:8175"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO_USER=${DOCKER_USER}
      - REPO_PASS=${DOCKER_PASSWORD}
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_TRACE=true
    command: --interval 30 --cleanup --debug --trace
    restart: unless-stopped

volumes:
  db-data:
    name: sims-db-data 