version: '3.8'

services:
  app:
    image: joshpigford/sims:latest
    volumes:
      - db-data:/app/db
    ports:
      - "5173:5173"
      - "8175:8175"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO_USER=${DOCKER_USER}
      - REPO_PASS=${DOCKER_PASSWORD}
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_TRACE=true
    command: --interval 30 --cleanup --debug --trace
    restart: unless-stopped

  backup:
    image: offen/docker-volume-backup:v2
    environment:
      BACKUP_CRON_EXPRESSION: "0 4 * * *"    # Runs at 4 AM daily
      BACKUP_RETENTION_DAYS: "7"             # Keep backups for 7 days
      BACKUP_FILENAME: "sims-backup-%Y-%m-%d"
    volumes:
      - db-data:/backup/sims-db:ro           # Mount the database volume
      - ./backups:/archive                   # Local folder to store backups
    depends_on:
      - app

volumes:
  db-data:
    name: sims-db-data 