version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: joshpigford/sims:latest
    pull_policy: always
    volumes:
      - db-data:/app/db
    ports:
      - "5173:5173"
      - "8175:8175"
    environment:
      - VITE_API_URL=http://homeserver.local:8175
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: unless-stopped

volumes:
  db-data:
    name: sims-db-data 