version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8175:8175"
    volumes:
      - ./db:/app/db
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8174:8174"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development
      - PORT=8174
    depends_on:
      - backend
    restart: unless-stopped 